// Generated by scripts/build-exe.js for spacehog 0.2.0.
import { run } from "../../src/cli.js";

// .then() rather than top-level await: esbuild cannot emit top-level await
// for the CommonJS format a Single Executable Application requires.
run(process.argv.slice(2))
  .then((code) => {
    process.exitCode = code;
  })
  .catch((error) => {
    console.error("spacehog: " + (error && error.stack ? error.stack : error));
    process.exitCode = 1;
  });
