// Generated by scripts/build-exe.js for spacehog 0.2.0.
import { run } from "../../src/cli.js";

// .then() rather than top-level await: esbuild cannot emit top-level await
// for the CommonJS format a Single Executable Application requires.
const argv = process.argv.slice(2);

function wantsCli(args) {
  if (args[0] === "--cli") return true;
  if (args.some((a) => ["--help", "-h", "--version", "-v"].includes(a))) return true;
  return args.some((a) => !a.startsWith("-"));
}

if (wantsCli(argv)) {
  const args = argv[0] === "--cli" ? argv.slice(1) : argv;
  run(args)
    .then((code) => {
      process.exitCode = code;
    })
    .catch((error) => {
      console.error("spacehog: " + (error && error.stack ? error.stack : error));
      process.exitCode = 1;
    });
} else {
  import("../../src/gui/server.js")
    .then(({ startGui, openInBrowser }) => startGui({ open: openInBrowser }))
    .then(() => {
      // Keep the process alive while the page is open; the browser is the window.
      setInterval(() => {}, 1 << 30);
    })
    .catch((error) => {
      console.error("spacehog GUI could not start: " + (error && error.message ? error.message : error));
      console.error("Run it with arguments instead, for example: spacehog.exe . --json");
      process.exitCode = 1;
    });
}
