'use strict';
// Generated by scripts/build-exe.js. The SEA main script must be CommonJS,
// and the CLI entry uses top-level await, so this waits for run() instead.
const { run } = require("./spacehog.cjs");
run(process.argv.slice(2))
  .then((code) => { process.exitCode = code; })
  .catch((error) => { console.error("spacehog: " + (error && error.stack ? error.stack : error)); process.exitCode = 1; });
