#!/usr/bin/env node
/**
 * Build standalone binaries with Node's Single Executable Application support.
 *
 *   Windows -> spacehog.exe      graphical front end, plus a CLI mode
 *   Linux   -> spacehog-cli      command line only, no GUI
 *
 * There is no third-party packager and no pkg: the project has no runtime
 * dependencies, so the only thing a bare Node binary is missing is the code.
 * esbuild bundles that into one CommonJS file (a SEA binary cannot require a
 * sibling file) and postject injects it into a copy of a Node runtime.
 *
 * macOS is deliberately not built: SEA output is unsigned and Gatekeeper turns
 * an unsigned binary into a "damaged app" dialog, which is worse than `npx`.
 *
 * Usage:
 *   node scripts/build-exe.js --target win
 *   node scripts/build-exe.js --target linux
 *   node scripts/build-exe.js --target win --node C:\path\to\node.exe
 */

import { spawnSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(fs.readFileSync(path.join(projectRoot, 'package.json'), 'utf8'));
const buildDir = path.join(projectRoot, 'tools', 'sea');

/**
 * A Node runtime to inject into. postject does not convert container formats,
 * so a Windows build needs a Windows node.exe and a Linux build needs a real
 * Linux ELF node. The embedded JavaScript is identical either way, which is
 * what makes cross-building from one machine possible.
 */
const BASE_NODE = {
  win: process.execPath,
  linux: path.join('D:', 'dsh', '_tools', 'node', 'node-v20.11.1-linux-x64', 'bin', 'node'),
};

/** What each target produces. Linux gets no GUI by design. */
const TARGETS = {
  win: {
    kind: 'gui',
    out: 'spacehog.exe',
    entry: 'src/gui/main.js',
    runnable: process.platform === 'win32',
    label: 'Windows GUI + CLI',
  },
  linux: {
    kind: 'cli',
    out: 'spacehog-cli',
    entry: 'src/cli.js',
    runnable: process.platform === 'linux',
    label: 'Linux command line',
  },
};

function flag(name, fallback = null) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : fallback;
}

function run(tool, args, options = {}) {
  const result =
    process.platform === 'win32'
      ? spawnSync('cmd', ['/c', tool, ...args], { encoding: 'utf8', ...options })
      : spawnSync(tool, args, { encoding: 'utf8', ...options });
  if (result.error || result.status !== 0) {
    const detail = result.error?.message ?? (result.stderr || result.stdout || '').trim();
    throw new Error(`${tool} ${args.join(' ')} failed: ${detail}`);
  }
  return result;
}

function bin(name) {
  return path.join(projectRoot, 'node_modules', '.bin', process.platform === 'win32' ? `${name}.cmd` : name);
}

/** esbuild cannot emit top-level await as CommonJS, so the CLI entry is wrapped. */
function writeWrapper(file, importLine, body) {
  fs.writeFileSync(
    file,
    [
      `// Generated by scripts/build-exe.js for spacehog ${pkg.version}.`,
      importLine,
      '',
      '// .then() rather than top-level await: esbuild cannot emit top-level await',
      '// for the CommonJS format a Single Executable Application requires.',
      ...body,
      '',
    ].join('\n'),
  );
}

function build(target, options) {
  const baseNode = options.node ?? BASE_NODE[target];
  const spec = options.spec;
  const outName = options.out ?? spec.out;
  console.log(`\n=== ${spec.label} -> ${outName} (spacehog ${pkg.version}) ===`);
  fs.mkdirSync(buildDir, { recursive: true });

  if (!fs.existsSync(bin('esbuild'))) throw new Error('esbuild is missing. Run: npm install');
  if (!fs.existsSync(bin('postject'))) throw new Error('postject is missing. Run: npm install');
  if (!fs.existsSync(baseNode)) throw new Error(`no base Node runtime for ${target}: ${baseNode}`);

  // 1. entry wrapper --------------------------------------------------------
  // The wrapper owns argv dispatch for the GUI build. Putting it here rather
  // than inside src/gui/main.js is what lets one binary answer `--cli` exactly
  // like the pure CLI build: the child process the GUI spawns is this same
  // executable, so the dispatch has to happen before any GUI code runs.
  const wrapper = path.join(buildDir, `entry-${target}.mjs`);
  if (spec.kind === 'gui') {
    writeWrapper(wrapper, 'import { run } from "../../src/cli.js";', [
      'const argv = process.argv.slice(2);',
      '',
      'function wantsCli(args) {',
      '  if (args[0] === "--cli") return true;',
      '  if (args.some((a) => ["--help", "-h", "--version", "-v"].includes(a))) return true;',
      '  return args.some((a) => !a.startsWith("-"));',
      '}',
      '',
      'if (wantsCli(argv)) {',
      '  const args = argv[0] === "--cli" ? argv.slice(1) : argv;',
      '  run(args)',
      '    .then((code) => {',
      '      process.exitCode = code;',
      '    })',
      '    .catch((error) => {',
      '      console.error("spacehog: " + (error && error.stack ? error.stack : error));',
      '      process.exitCode = 1;',
      '    });',
      '} else {',
      '  import("../../src/gui/server.js")',
      '    .then(({ startGui, openInBrowser }) => startGui({ open: openInBrowser }))',
      '    .then(() => {',
      '      // Keep the process alive while the page is open; the browser is the window.',
      '      setInterval(() => {}, 1 << 30);',
      '    })',
      '    .catch((error) => {',
      '      console.error("spacehog GUI could not start: " + (error && error.message ? error.message : error));',
      '      console.error("Run it with arguments instead, for example: spacehog.exe . --json");',
      '      process.exitCode = 1;',
      '    });',
      '}',
    ]);
  } else {
    writeWrapper(wrapper, 'import { run } from "../../src/cli.js";', [
      'run(process.argv.slice(2))',
      '  .then((code) => {',
      '    process.exitCode = code;',
      '  })',
      '  .catch((error) => {',
      '    console.error("spacehog: " + (error && error.stack ? error.stack : error));',
      '    process.exitCode = 1;',
      '  });',
    ]);
  }

  // 2. one CommonJS bundle --------------------------------------------------
  const bundle = path.join(buildDir, `bundle-${target}.cjs`);
  run(
    bin('esbuild'),
    [
      wrapper,
      '--bundle',
      '--platform=node',
      '--format=cjs',
      '--target=node18',
      '--external:node:*',
      `--outfile=${bundle}`,
      '--log-level=warning',
      `--banner:js=// spacehog ${pkg.version} (${spec.kind}) — bundled from src/`,
    ],
    { cwd: projectRoot },
  );
  console.log(`  bundled -> ${(fs.statSync(bundle).size / 1024).toFixed(1)} KB`);

  // Guards: the bundle must contain the real logic, and must not try to require
  // a sibling file, which a SEA binary cannot resolve.
  const bundleText = fs.readFileSync(bundle, 'utf8');
  const markers = ['findDuplicates', 'suggestKeep', 'renderMarkdown', 'parseArgs'];
  if (spec.kind === 'gui') markers.push('startGui', 'api/run');
  for (const marker of markers) {
    if (!bundleText.includes(marker)) throw new Error(`bundle is missing "${marker}"`);
  }
  if (/require\(["']\.\//.test(bundleText)) {
    throw new Error('bundle still contains a relative require; a SEA binary cannot resolve siblings');
  }

  // 3. SEA blob -------------------------------------------------------------
  const seaConfig = path.join(buildDir, `sea-${target}.json`);
  const blob = path.join(buildDir, `spacehog-${target}.blob`);
  fs.writeFileSync(
    seaConfig,
    `${JSON.stringify(
      {
        main: path.relative(projectRoot, bundle).split(path.sep).join('/'),
        output: path.relative(projectRoot, blob).split(path.sep).join('/'),
        disableExperimentalSEAWarning: true,
        useSnapshot: false,
        useCodeCache: false,
      },
      null,
      2,
    )}\n`,
  );
  run(process.execPath, ['--experimental-sea-config', seaConfig], { cwd: projectRoot });

  // 4. inject ---------------------------------------------------------------
  const output = path.join(buildDir, outName);
  fs.copyFileSync(baseNode, output);
  fs.chmodSync(output, 0o755);
  run(
    bin('postject'),
    [output, 'NODE_SEA_BLOB', blob, '--sentinel-fuse', 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2'],
    { cwd: projectRoot },
  );

  const head = fs.readFileSync(output).subarray(0, 4);
  const format = head[0] === 0x7f && head[1] === 0x45 ? 'ELF' : head[0] === 0x4d && head[1] === 0x5a ? 'PE' : 'unknown';
  const size = fs.statSync(output).size;
  const sha = crypto.createHash('sha256').update(fs.readFileSync(output)).digest('hex');
  fs.writeFileSync(path.join(buildDir, `${outName}.sha256`), `${sha}  ${outName}\n`);
  console.log(`  wrote ${outName} (${(size / 1048576).toFixed(1)} MB, ${format})`);
  console.log(`  sha256 ${sha}`);
  return { output, outName, format, size, sha, runnable: spec.runnable, kind: spec.kind };
}

/** Run what this machine can actually execute. */
function selfTest(result) {
  if (!result.runnable) {
    console.log(`  self-test skipped: ${result.format} binary cannot run on ${process.platform}`);
    return;
  }
  const version = run(result.output, ['--version'], { cwd: buildDir }).stdout.trim();
  if (version !== pkg.version) {
    throw new Error(`${result.outName} reports "${version}", expected "${pkg.version}"`);
  }
  console.log(`  self-test: --version -> ${version}`);
  if (result.kind === 'gui') {
    const cli = run(result.output, ['--cli', '--help'], { cwd: buildDir }).stdout;
    if (!/Usage/.test(cli)) throw new Error('GUI binary does not answer --cli --help with the CLI usage text');
    console.log('  self-test: --cli --help -> CLI mode reached');
  }
}

function main() {
  const target = flag('--target', process.platform === 'win32' ? 'win' : 'linux');
  const spec = TARGETS[target];
  if (!spec) throw new Error(`unknown target "${target}" (expected win or linux)`);

  const result = build(target, { spec, node: flag('--node', null), out: flag('--out', null) });
  selfTest(result);
  console.log(`\n${result.outName} ready in ${path.relative(projectRoot, buildDir)}`);
  return 0;
}

try {
  process.exitCode = main();
} catch (error) {
  console.error(`build failed: ${error.message}`);
  process.exitCode = 1;
}
